JuliaSearleTennis/Controllers/AdultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class AdultsController : Controller
    {
        public ActionResult Booking()
        {
            return View();
        }
        public ActionResult BookNowSummer2015()
        {
            return View();
        }
        
        public ActionResult Cardio()
        {
            return View();
        }
        
        public ActionResult CourseSyllabus()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }      

        public ActionResult GroupProgramme()
        {
            return View();
        }

        public ActionResult TeamTraining()
        {
            return View();
        }

        public ActionResult TermDates()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/CampsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class CampsController : Controller
    {
        public ActionResult BookNow()
        {
            return View();
        }

        public ActionResult Dates()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }

        public ActionResult Schedule()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/JuniorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class JuniorsController : Controller
    {
        public ActionResult BookNowSummer2015()
        {
            return View();
        }
        public ActionResult BookNowAutumn2015()
        {
            return View();
        }
        public ActionResult CourseSyllabus()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }
        public ActionResult GroupCoaching()
        {
            return View();
        }

        public ActionResult Junior()
        {
            return View();
        }
        public ActionResult MiniTennis()
        {
            return View();
        }

        public ActionResult Performance()
        {
            return View();
        }

        public ActionResult PrivateLessons()
        {
            return View();
        }
        public ActionResult TermDates()
        {
            return View();
        }

        public ActionResult TennisLeaders()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }

        public ActionResult Tots()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/OtherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class OtherController : Controller
    {
        // GET: Other
       

        public ActionResult About()
        {
            return View();
        }

        public ActionResult BookingConfirmation()
        {
            return View();
        }

        public ActionResult BookSpring2016()
        {
            return View();
        }
        
        public ActionResult ContactUs()
        {
            return View();
        }

        public ActionResult ContactUsResponse()
        {
            return View();
        }

        public ActionResult Policies()
        {
            return View();
        }

        public ActionResult Recruitment()
        {
            return View();
        } 
        
        public ActionResult Restringing()
        {
            return View();
        }

        public ActionResult Tips()
        {
            return View();
        }

        public ActionResult Holidays()
        {
            return View();
        }

        public ActionResult WaitingForm()
        {
            return View();
        }

        public ActionResult WaitingResponse()
        {
            return View();
        }

      

        public ActionResult MailingListResponse()
        {
            return View();
        }

       


    }
}

JuliaSearleTennis/Views/Other/About.cshtml
@{
    ViewBag.Title = "About Us";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>About JTennis</h2></div>

    <p>JTennis was founded in 2015 by Julia Searle.
    <br/>Our mission is to get more people in Britain playing more tennis by making tennis more accessible, more affordable and more fun.
    </p>
    <ul class="list-unstyled">
        Our values:
        <li><i class="fa fa-check color-green"></i>	To provide professional and consistent customer service</li>
        <li><i class="fa fa-check color-green"></i>	To provide top quality tennis coaching</li>
        <li><i class="fa fa-check color-green"></i>	To provide a consistent customer experience regardless of age, ability or background</li>
        <li><i class="fa fa-check color-green"></i>	To remain focussed on our mission</li>
        <li><i class="fa fa-check color-green"></i>	To never stop developing</li>
    </ul>
</div>

JuliaSearleTennis/Views/Other/BookingConfirmation.cshtml
@{
    ViewBag.Title = "Booking confirmation";
    Layout = "~/Views/_LayoutPage.cshtml";
}




<div class="container content">


    <div class="headline"><h2>Confirmation</h2></div>

    <div class="row">

        <p>
           Thank you for your booking. Your payment has been received and your transaction is now complete. 
        </p>
        <p>
           Before attending please ensure you have read the following where relevant:
            <ul class="list-unstyled">
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("Policies","Other")">Policies</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("Terms","Juniors")">Terms and conditions for junior groups</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("Terms","Adults")">Terms and conditions for adult groups</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("Terms","Camps")">Terms and conditions for holiday camps</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("FAQ","Adults")">FAQs for adult groups</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("FAQ","Juniors")">FAQs for junior groups</a></li>
                <li><i class="fa fa-check color-green"></i><a href="@Url.Action("FAQ","Camps")">FAQs for holiday camps</a></li>
            </ul>
        </p>
       <p>
           If you have any other questions please contact <a href="mailto:julia@tenniscoaching.london">julia@tenniscoaching.london</a>
       </p>
    </div>
    <div>
       
    </div>
  
</div>
  

JuliaSearleTennis/Views/Other/ContactUs.cshtml
@{
    ViewBag.Title = "Contact Us";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/assets/plugins/sky-forms/version-2.0.1/css/custom-sky-forms.css")">

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        <form action="~/form2email/formmail.asp" method="post" id="sky-form3" class="sky-form">
            <input name="recipients_old" type="hidden" value="info&#64;\\web-123win\winpackage23\tenniscoaching.london\www.tenniscoaching.london\web\content\form2email\setup_script.cgi" />
            <input name="_requiredFields" type="hidden" value="Name,Email,Comments" />
            <input name="_envars" type="hidden" value="HTTP_USER_AGENT,REMOTE_ADDR" />
            <input name="_returnUrl" type="hidden" value="default.asp" />
            <input name="_continueUrl" type="hidden" value="default.asp" />
            <header>Contact us form</header>

            <fieldset>
                <div class="row">
                    <section class="col col-6">
                        <label class="label">Name</label>
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>
                            <input type="text" name="name" id="name">
                        </label>
                    </section>
                    <section class="col col-6">
                        <label class="label">E-mail</label>
                        <label class="input">
                            <i class="icon-append fa fa-envelope-o"></i>
                            <input type="email" name="email" id="email">
                        </label>
                    </section>
                </div>

                <section>
                    <label class="label">Subject</label>
                    <label class="input">
                        <i class="icon-append fa fa-tag"></i>
                        <input type="text" name="subject" id="subject">
                    </label>
                </section>

                <section>
                    <label class="label">Message</label>
                    <label class="textarea">
                        <i class="icon-append fa fa-comment"></i>
                        <textarea rows="4" name="comments" id="comments"></textarea>
                    </label>
                </section>

            </fieldset>

            <footer>
                <input type="hidden" name="_redirectUrl" value="@Url.Action("ContactUsResponse", "Other")" />"
                <input type="submit" value="Send message" class="button">
            </footer>

            <div class="message">
                <i class="rounded-x fa fa-check"></i>
                <p>Your message was successfully sent!</p>
            </div>
        </form>
        <!-- Contacts -->

    </div>
</div>
<script type="text/javascript" src="@Url.Content("~/assets/js/pages/page_contact_advanced.js")"></script>

<script type="text/javascript">
    jQuery(document).ready(function () {
        App.init();
        PageContactForm.initPageContactForm();
    });
</script>

JuliaSearleTennis/Views/Other/ContactUsResponse.cshtml
@{
    ViewBag.Title = "Contact response";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>Form Submission</h2></div>

    <p>Thank you for contacting us, we will be back in touch shortly.
    </p>

</div>

JuliaSearleTennis/Views/Other/Holidays.cshtml
@{
    ViewBag.Title = "Holidays";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <h2>Tours and Holidays</h2>


            <p>
                This years programme will include:
                <ul class="list-unstyled">
                    <li><i class="color-green fa fa-check"></i>International training camp for the more serious player</li>
                    <li><i class="color-green fa fa-check"></i>A UK junior tournament week</li>
                    <li><i class="color-green fa fa-check"></i>A relaxing tennis holiday abroad</li>
                </ul>

            </p>
        </div>

        <div class="col-md-3">
            <img class="img-responsive" src="@Url.Content("~/img/tenerife-at-night.jpg")" alt="" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
        <div class="headline">
            <h2>
                Tennis Training Camp in Tenerife - October 2015</h2></div>
                <h4>About the Camp</h4>
                <p>
                    Come away with us to our tennis camp, giving you the opportunity to immerse yourself in a tailor-made intensive programme while taking a break and enjoying a holiday at the same time.
                    Our camp is designed for our stronger adult players (high team standard or equivalent), as well as our performance juniors. It is open to Wigmore members and non members alike.
                    The camp is led by George Cupsa, former ATP world ranked player and coach to several WTA world top 100 players.
                </p>
                <h4>When and Where?</h4>
                <ul class="list-unstyled">
                    <li>
                        <i class="color-green fa fa-check"></i>
                        20th – 27th October 2015
                    </li>
                    <li> <i class="color-green fa fa-check"></i>	Playa de las Americas, Tenerife</li>
                </ul>
                <h4>What is Included?</h4>
                <ul class="list-unstyled">
                    <li> <i class="color-green fa fa-check"></i>	Return flights from London-Gatwick</li>
                    <li> <i class="color-green fa fa-check"></i>	7 nights accommodation at the 4* Hotel H10 Las Palmeras</li>
                    <li> <i class="color-green fa fa-check"></i>	Twin room accommodation with a balcony or terrace</li>
                    <li> <i class="color-green fa fa-check"></i>	All-Inclusive package</li>
                    <li> <i class="color-green fa fa-check"></i>	2-3 hours of training per day (total of 15 hours) with a maximum coach player ratio of 1:4</li>
                    <li> <i class="color-green fa fa-check"></i>	Unlimited additional court time per day (subject to court availability)</li>
                    <li> <i class="color-green fa fa-check"></i>	Airport transfer to and from hotel</li>

                </ul>
                <h4>About the Hotel</h4>
                <ul class="list-unstyled">
                    For more information please visit the <a href="https://www.h10hotels.com/en/tenerife-hotels/h10-las-palmeras/"> resort website</a>
                    <li> <i class="color-green fa fa-check"></i>	4 * Accommodation</li>
                    <li> <i class="color-green fa fa-check"></i>	Next to the sea with direct access to the seafront</li>
                    <li> <i class="color-green fa fa-check"></i>	3 outdoor swimming pools</li>
                    <li> <i class="color-green fa fa-check"></i>	Air conditioned gym</li>
                    <li> <i class="color-green fa fa-check"></i>	Average October temperature is 22 degrees</li>
                </ul>

               
            </div>
        <div class="col-md-3">
            <!-- Contacts -->
            <div class="headline"><h2>How to Register?</h2></div>
            <a href="https://payableform.appspot.com/forms/jjp6a">Book here</a>
            <p>   The cost of the tennis camp is £1200.
            <br />To reserve your place, a non-refundable deposit of £350 by the 1st August.
            <br/>The balance is due by the 1st September.
            <br />Places are limited.
            <br />Non-tennis playing partners/friends are also welcome to attend. The cost of the holiday excluding the tennis training is £900.

            <img class="img-responsive" src="@Url.Content("~/img/tenerife-site-overview.jpg")" alt="" />
            <img class="img-responsive" src="@Url.Content("~/img/tenerife-tennis-court.jpg")" alt="" />
            </p>
        </div>
        </div>
    </div>

JuliaSearleTennis/Views/Other/MailingListResponse.cshtml
@{
    ViewBag.Title = "Mailing list response";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>Mailing list submission</h2></div>

    <p>Thank you for contacting us, you have been added to our mailing lists.
    </p>
    <p>We will contact you from time to time with details of our upcoming courses and events.</p>

</div>

JuliaSearleTennis/Views/Other/Recruitment.cshtml
@{
    ViewBag.Title = "Recruitment";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>Working at JTennis</h2></div>

    <p>We are always on the lookout for individuals to join our fantastic team of tennis coaches.
    </p>
    <ul class="list-unstyled">Are you:
    <li><i class="fa fa-check color-green"></i>Passionate about tennis?</li>
    <li><i class="fa fa-check color-green"></i>Motivated to be best coach that you can be?</li>
    <li><i class="fa fa-check color-green"></i>Willing to go the extra mile to develop each of your players?</li>
        </ul>
    <ul class="list-unstyled">
    Do you:
        <li><i class="fa fa-check color-green"></i>	Want to be part of a team?</li>
        <li><i class="fa fa-check color-green"></i>	Have excellent communication skills?</li>
        <li><i class="fa fa-check color-green"></i>	Have a friendly personality and a sense of humour?</li>
        </ul>
    <p>
        If you think you have what it takes to become a coach at JTennis, please email <a href="mailto:julia@tenniscoaching.london">julia@tenniscoaching.london</a>
    </p>
</div>

JuliaSearleTennis/Views/Other/Restringing.cshtml
@{
    ViewBag.Title = "Restringing";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>Our Restringing Services</h2></div>

    <div class="row">
        <div class="col-md-9">



            <h3>Restringing services</h3>
            <div class="panel panel-purple margin-bottom-40">

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>String type</th>
                            <th>Price</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>provide own string</td>
                            <td>£12.50</td>      
                        </tr>
                   
                       <tr><td>Gamma Synthetic Gut:                      </td><td> £20 </td></tr>
                       <tr><td>Prince Synthetic Gut with duraflex:       </td><td> £20 </td></tr>
                       <tr><td>Babolat Addiction                         </td><td> £22 </td></tr>
                       <tr><td>Babolat RPM Team                          </td><td> £25 </td></tr>
                       <tr><td>Prince Premier Control                    </td><td> £25 </td></tr>
                       <tr><td>Technifibre Red Code                      </td><td> £25 </td></tr>
                       <tr><td>Technifibre Black Code                       </td><td> £25 </td></tr>                                                       
                       <tr><td colspan="2">We can also offer a 24-hour turnaround for an additional £3.00</td></tr>


                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-3">
                <!-- Contacts -->
                <div class="headline"><h2>Contact</h2></div>
                If you would like further information, or to arrange a restringing please contact:
                <ul class="list-unstyled who margin-bottom-30">
                    <li><a href="#"><i class="fa fa-home"></i>Head stringer: Julia</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i>julia@tenniscoaching.london</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i>07816 004 992</a></li>
                   
                </ul>
                <img class="img-responsive" src="@Url.Content("~/img/ersa-logo.jpg")" alt="" />

            </div>
    </div>
</div>

JuliaSearleTennis/Views/Other/Tips.cshtml
@{
    ViewBag.Title = "Tips";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<h2>Tips</h2>

<p>Details to follow</p>

JuliaSearleTennis/Views/Other/WaitingForm.cshtml
@{
    ViewBag.Title = "Contact Us";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/assets/plugins/sky-forms/version-2.0.1/css/custom-sky-forms.css")">

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        <form action="~/form2email/formmail.asp" method="post" id="sky-form3" class="sky-form">
            <input name="recipients_old" type="hidden" value="info&#64;\\web-123win\winpackage23\tenniscoaching.london\www.tenniscoaching.london\web\content\form2email\setup_script.cgi" />
            <input name="_requiredFields" type="hidden" value="Name,Email,Comments" />
            <input name="_envars" type="hidden" value="HTTP_USER_AGENT,REMOTE_ADDR" />
            <input name="_returnUrl" type="hidden" value="default.asp" />
            <input name="_continueUrl" type="hidden" value="default.asp" />
            <header>Waiting list form</header>
            Please complete the following form and we'll add you to our waiting lists.
            <fieldset>
                <div class="row">
                    <section class="col col-6">
                        <label class="label">Name</label>
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>
                            <input type="text" name="name" id="name">
                        </label>
                    </section>
                    <section class="col col-6">
                        <label class="label">E-mail</label>
                        <label class="input">
                            <i class="icon-append fa fa-envelope-o"></i>
                            <input type="email" name="email" id="email">
                        </label>
                    </section>
                </div>

                <section>
                    <label class="label">Class to be added to the waiting list</label>
                    <label class="input">
                        <i class="icon-append fa fa-tag"></i>
                        <input type="text" name="subject" id="subject">
                    </label>
                </section>

                <section>
                    <label class="label">Any other information</label>
                    <label class="textarea">
                        <i class="icon-append fa fa-comment"></i>
                        <textarea rows="4" name="comments" id="comments"></textarea>
                    </label>
                </section>

            </fieldset>

            <footer>
                <input type="hidden" name="_redirectUrl" value="@Url.Action("WaitingResponse", "Other")" />"
                <input type="submit" value="Send message" class="button" />
            </footer>

            <div class="message">
                <i class="rounded-x fa fa-check"></i>
                <p>Your message was successfully sent!</p>
            </div>
        </form>
        <!-- Contacts -->

    </div>
</div>
<script type="text/javascript" src="@Url.Content("~/assets/js/pages/page_contact_advanced.js")"></script>

<script type="text/javascript">
    jQuery(document).ready(function () {
        App.init();
        PageContactForm.initPageContactForm();
    });
</script>

JuliaSearleTennis/Views/Other/WaitingResponse.cshtml
@{
    ViewBag.Title = "Waiting list response";
    Layout = "~/Views/_LayoutPage.cshtml";
}


<!--=== Content Part ===-->
<div class="container content">
    <div class="headline"><h2>Waiting list submission</h2></div>

    <p>Thank you for contacting us, you have been added to our waiting lists.
    </p>
    <p>If an exisitng booking is cancelled we will offer you a place. Alternatively we will endeavour to create new classes where there is sufficient demand, thank you for your patience.</p>

</div>