JuliaSearleTennis/Controllers/CampsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class CampsController : Controller
    {
        public ActionResult BookNow()
        {
            return View();
        }

        public ActionResult Dates()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }

        public ActionResult Schedule()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/OtherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class OtherController : Controller
    {
        // GET: Other
       

        public ActionResult About()
        {
            return View();
        }

        public ActionResult BookingConfirmation()
        {
            return View();
        }

        public ActionResult BookSpring2016()
        {
            return View();
        }
        
        public ActionResult ContactUs()
        {
            return View();
        }

        public ActionResult ContactUsResponse()
        {
            return View();
        }

        public ActionResult Policies()
        {
            return View();
        }

        public ActionResult Recruitment()
        {
            return View();
        } 
        
        public ActionResult Restringing()
        {
            return View();
        }

        public ActionResult Tips()
        {
            return View();
        }

        public ActionResult Holidays()
        {
            return View();
        }

        public ActionResult WaitingForm()
        {
            return View();
        }

        public ActionResult WaitingResponse()
        {
            return View();
        }

      

        public ActionResult MailingListResponse()
        {
            return View();
        }

       


    }
}

JuliaSearleTennis/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult OurCoachingTeam()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Views/Shared/_CSSSupport.cshtml
 <!-- CSS Global Compulsory -->
<link rel="stylesheet" href="@Url.Content("~/assets/plugins/bootstrap/css/bootstrap.min.css")">
<link rel="stylesheet" href="@Url.Content("~/assets/css/style.css")">

<!-- CSS Implementing Plugins -->
<link rel="stylesheet" href="@Url.Content("~/assets/plugins/line-icons/line-icons.css")">
<link rel="stylesheet" href="@Url.Content("~/assets/plugins/font-awesome/css/font-awesome.min.css")">

<!-- CSS Theme -->
<link rel="stylesheet" href="@Url.Content("~/assets/css/theme-colors/blue.css")">

<link rel="stylesheet" href="@Url.Content("~/assets/css/pages/page_job.css")">

<!-- CSS Customization -->
<link rel="stylesheet" href="@Url.Content("~/assets/css/custom.css")">

JuliaSearleTennis/Views/Shared/_Contact.cshtml
<div class="headline"><h2>Contact</h2></div>
<ul class="list-unstyled who margin-bottom-30">
    <li><a href="#"><i class="fa fa-home"></i>Venue: Wigmore Tennis Club</a></li>
    <li><a href="#"><i class="fa fa-envelope"></i>julia@tenniscoaching.london</a></li>
    <li><a href="#"><i class="fa fa-phone"></i></a></li>
</ul>

JuliaSearleTennis/Views/Shared/_Footer.cshtml
 
<div class="footer-v2">
    <div class="footer">
        <div class="container">
            <div class="row">
             
                <div class="col-md-2 md-margin-bottom-40">
                    <a href="index.html"><img id="logo-footer" class="footer-logo" href="@Url.Content("~/assets/img/logo2-default.png")" alt=""></a>

                </div>
                <div class="col-md-3 md-margin-bottom-40">
                    <div class="headline"><h2>Useful Links</h2></div>
                    <ul class="list-unstyled link-list">
                        <li><a href="@Url.Action("About","Other")">About us</a><i class="fa fa-angle-right"></i></li>
                        <li><a href="@Url.Action("Recruitment","Other")">Work for JTennis</a><i class="fa fa-angle-right"></i></li>
                        <li><a href="@Url.Action("ContactUs","Other")">Contact us</a><i class="fa fa-angle-right"></i></li>
                    </ul>
                </div>
                <div class="col-md-3 md-margin-bottom-40">
                    <div class="headline"><h2>Office hours</h2></div>
                    <strong></strong>
                    <ul class="list-unstyled link-list">
                        <li>Monday 1.30-5.30</li>
                        <li>Tuesday 9.30-12.30</li>
                        <li>Wednesday 1.30-5.30</li>
                        <li>Thursday 1.30-5.30</li>
                        <li>Friday 9.30-12.30</li>
                        <li>Saturday 12-6</li>
                    </ul>
                </div>
               
                <div class="col-md-3 map-img md-margin-bottom-40">
                    <div class="headline"><h2>Contact Us</h2></div>
                    <address class="md-margin-bottom-40">
                       Wigmore Tennis Club <br />
                        43 Becmead Avenue<br />
                        SW16 1UJ<br />
                       

                        Email: <a href="mailto:joe@tenniscoaching.london">joe@tenniscoaching.london</a> (acting head coach)

                        <br /><a href="mailto:julia@tenniscoaching.london">julia@tenniscoaching.london</a> (head coach currently on maternity leave until early 2017)
                       
                        <br />
                        
                    </address>
                </div><!--/col-md-3-->
                <!-- End Address -->
            </div>
        </div>
    </div><!--/footer-->

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>
                        2015 &copy; All Rights Reserved.
                        <a href="@Url.Action("Policies","Other")">Our Policies</a> | 
                    </p>
                </div>

                <!-- Social Links -->
                <div class="col-md-6">
                    <ul class="footer-socials list-inline">
                        <li>
                            <a href="https://www.facebook.com/pages/JTennis/1377833565863509" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>

                        <li>
                            <a href="http://uk.linkedin.com/pub/julia-searle/38/898/95a" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>

                        <li>
                            <a href="https://twitter.com/julia_tennis" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>

                    </ul>
                </div>
                <!-- End Social Links -->
            </div>
        </div>
    </div><!--/copyright-->
</div>

JuliaSearleTennis/Views/Shared/_JSSupport.cshtml
 <!-- JS Global Compulsory -->
<script type="text/javascript" src="@Url.Content("~/assets/plugins/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/assets/plugins/jquery/jquery-migrate.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/assets/plugins/bootstrap/js/bootstrap.min.js")"></script>
<!-- JS Implementing Plugins -->
<script type="text/javascript" src="@Url.Content("~/assets/plugins/back-to-top.js")"></script>


<!-- JS Customization -->
<script type="text/javascript" src="@Url.Content("~/assets/js/custom.js")"></script>
<!-- JS Page Level -->
<script type="text/javascript" src="@Url.Content("~/assets/js/app.js")"></script>



<!--[if lt IE 9]>
    <script src="@Url.Content("~/assets/plugins/respond.js")"></script>
    <script src="@Url.Content("~/assets/plugins/html5shiv.js")"></script>
    <script src="@Url.Content("~/assets/js/plugins/placeholder-IE-fixes.js")"></script>
<![endif]-->

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-61301686-1', 'auto');
    ga('send', 'pageview');

</script>

JuliaSearleTennis/Views/Shared/_TopNavigation.cshtml
<!--=== Header ===-->

<div class="header">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">

        </div>
    </div>
    <!-- End Topbar -->
    <!-- Navbar -->
    <div class="navbar navbar-default mega-menu" role="navigation" >
        <!--<i class="icon-custom icon-color-dark rounded-x fa fa-home"></i>-->
        <div class="container">
          
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="fa fa-bars"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                    <img id="logo-header" src="@Url.Content("~/img/JTennis_logo-horiz-small.png")" alt="Logo">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                   
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Adults
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("GroupProgramme","Adults")">Our group programme</a></li>
                            <li><a href="@Url.Action("TeamTraining","Adults")">Team training</a></li>
                            <li><a href="@Url.Action("Cardio","Adults")">Cardio Tennis</a></li>
                            <li><a href="@Url.Action("PrivateLessons","Juniors")">Private Lessons</a></li>
                            <li><a href="@Url.Action("TermDates","Adults")">Term dates</a></li>   
                            <li><a href="@Url.Action("CourseSyllabus","Adults")">Course Syllabus</a></li>
                            <li><a href="@Url.Action("FAQ","Adults")">FAQ</a></li>
                            <li><a href="@Url.Action("Terms","Adults")">Terms and conditions</a></li>
                        </ul>
                    </li>

                    <!-- End Pages -->
                    <!-- Features -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Juniors
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Tots","Juniors")">Tots Tennis (3-4yrs)</a></li>
                            <li><a href="@Url.Action("MiniTennis","Juniors")">Mini Tennis (5-11yrs)</a></li>
                            <li><a href="@Url.Action("Junior","Juniors")">Junior Tennis (11-17yrs)</a></li>
                            <li><a href="@Url.Action("TennisLeaders","Juniors")">Tennis Leaders (14yrs+)</a></li>
                            <li><a href="@Url.Action("PrivateLessons","Juniors")">Private Lessons</a></li>
                            <li><a href="@Url.Action("Performance","Juniors")">Performance / Academy</a></li>
                            <li><a href="@Url.Action("TermDates","Adults")">Term dates</a></li>         
                            <li><a href="@Url.Action("CourseSyllabus","Juniors")">Course Syllabus</a></li>
                            <li><a href="@Url.Action("FAQ","Juniors")">FAQ</a></li>
                            <li><a href="@Url.Action("Terms","Juniors")">Terms and conditions</a></li>

                        </ul>
                    </li>

                    <!-- End Features -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Camps
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Dates","Camps")">Camp dates</a></li>
                            <li><a href="@Url.Action("BookNow","Camps")">Book now</a></li>
                            <li><a href="@Url.Action("Schedule","Camps")">Schedule</a></li>
                            <li><a href="@Url.Action("FAQ","Camps")">FAQ</a></li>
                            <li><a href="@Url.Action("Terms","Camps")">Terms and conditions</a></li>
                        </ul>
                    </li>
                    <!-- Blog -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Community
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("SchoolsProgramme","Community")">Our school programme</a></li>
                            <li><a href="@Url.Action("LondonYouthGames","Community")">London Youth Games</a></li>
                        </ul>
                    </li>
                    <!-- End Blog -->
                    <!-- Contacts -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Venues
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Wigmore","Venues")">Wigmore LTC (Streatham)</a></li>
                            <li><a href="@Url.Action("Camber","Venues")">Camber LTC (East Dulwich)</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            Our team
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("OurCoachingTeam","Team")">About our team</a></li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                           Compete
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Tournaments","Compete")">Tournaments</a></li>
<!--
                            <li><a href="@Url.Action("MatchPlay","Compete")">Matchplay</a></li>
                            <li><a href="@Url.Action("Leagues","Compete")">Leagues</a></li>
                            <li><a href="@Url.Action("Teams","Compete")">Teams</a></li>
-->
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="@Url.Action("Index","Shop")">
                            Shop
                        </a>     
                    </li>
                </ul>
            </div><!--/navbar-collapse-->
        </div>
    </div>
    <!-- End Navbar -->
</div>

<!--=== End Header ===-->