JuliaSearleTennis/Controllers/BookingCamberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class BookingCamberController : Controller
    {
        
        public ActionResult Red()
        {
            return View();
        }

        public ActionResult Orange()
        {
            return View();
        }

        public ActionResult Green()
        {
            return View();
        } 

        public ActionResult PrivateLessons()
        {
            return View();
        }

        public ActionResult Juniors()
        {
            return View();
        }

        public ActionResult Tots()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class BookingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TenLessons()
        {
            return View();
        }

        public ActionResult PrivateLessons()
        {
            return View();
        }

       

        // GET: Booking
        public ActionResult Tots()
        {
            return View();
        }

        public ActionResult Red()
        {
            return View();
        }

        public ActionResult Orange()
        {
            return View();
        }

        public ActionResult Green()
        {
            return View();
        }

        public ActionResult Adults()
        {
            return View();
        }

        public ActionResult Juniors()
        {
            return View();
        }

        public ActionResult TeamTraining()
        {
            return View();
        }

        public ActionResult Cardio()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/JuniorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class JuniorsController : Controller
    {
        public ActionResult BookNowSummer2015()
        {
            return View();
        }
        public ActionResult BookNowAutumn2015()
        {
            return View();
        }
        public ActionResult CourseSyllabus()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }
        public ActionResult GroupCoaching()
        {
            return View();
        }

        public ActionResult Junior()
        {
            return View();
        }
        public ActionResult MiniTennis()
        {
            return View();
        }

        public ActionResult Performance()
        {
            return View();
        }

        public ActionResult PrivateLessons()
        {
            return View();
        }
        public ActionResult TermDates()
        {
            return View();
        }

        public ActionResult TennisLeaders()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }

        public ActionResult Tots()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuliaSearleTennis.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult OurCoachingTeam()
        {
            return View();
        }
    }
}

JuliaSearleTennis/Views/Juniors/Junior.cshtml
@{
    ViewBag.Title = "Junior Tennis";
    Layout = "~/Views/_LayoutPage.cshtml";
}
<link href="@Url.Content("~/CSS/BookingButtons.css")" rel="stylesheet" />
<link href="@Url.Content("~/CSS/JuniorBookingButtons.css")" rel="stylesheet" />
<!--=== Content Part ===-->
<div class="container content">
    <div class="row margin-bottom-40">
        <div class="col-md-6 md-margin-bottom-40">
            <h2>Junior tennis (age 11 - 17yrs)</h2>
            <p>We offer a weekly tennis programme for juniors of all levels and ages. Our programme is structered to allow avery player to improve their skills, wether 
            they are looking for a relaxed and socialable environment with their friends or high intensity training in order to reach the next level of competition.</p>
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-check color-green"></i> Maximum Ratio of 1:8
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Full court size and yellow ball
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Technical and tactical coaching
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	<a href="@Url.Action("CourseSyllabus", "Juniors")"><span style="color:#3498db;">Tailormade syllabus</span></a> to maximise development
                </li>
           </ul>


               
        </div>
        <div class="col-md-6 md-margin-bottom-40">
            <div class="thumbnail-style">
                <img src="@Url.Content("~/img/juniors-landscape1.jpg")" class="img-responsive" />
            </div>
        </div>
    </div><!--/row-->
    <div class="row">

        <div class="row md-margin-bottom-40">
            Please note that all players who participate in the coaching programme MUST either be members of the club OR pay a guest fee to the club.
            Once your coaching registration is complete, the club will send you details regarding guest fee payment or membership application.
            The guest fee payable is equal to £1.50 per session for juniors and £2.50 per session for adults.
        </div>
        <script src="https://d3gxy7nm8y4yjr.cloudfront.net/js/embed.js" type="text/javascript"></script>
        <table cellspacing="5" class="table table-striped">
            <thead>
                <tr>

                    <th>Spring 2017 Wigmore classes</th>
                    <th>Autumn 2016 Camber classes</th>

                </tr>

            </thead>

            <tbody>
                <tr>
                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>MONDAY 5pm Age 11-14</li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 4pm Age 10-12</li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 6pm (girls only, Age 11-14)</li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 6pm Age 11-14</li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 7pm Age 14-18</li>
                            <li><i class="fa fa-check color-green"></i>FRIDAY 5pm (girls only) </li>
                            <li><i class="fa fa-check color-green"></i>SATURDAY 1pm (girls only)</li>
                        </ul><a href="@Url.Action("Juniors","Booking")" class="Yellow">Book a Wigmore class</a>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>MONDAY 5:30pm Age 13-15 </li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 5:30pm Age 13-15 </li>
                            <li><i class="fa fa-check color-green"></i>SATURDAY 3:30pm Age 12-15</li>
                            <li><i class="fa fa-check color-green"></i>SATURDAY 4:30pm Age 14-17</li>
                        </ul>
                        <a href="@Url.Action("Juniors","BookingCamber")" class="Yellow">Book a Camber class</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        If the course you wish to enrol for is fully booked you can join a waiting list.
                        <a href="https://docs.google.com/forms/d/1YlmozTfmfFfxmp_c1yQRKEs6rZazMI6b_MXxl510Jw4/viewform?usp=send_form" class="TotsMini">Join a waiting list</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">Finding booking difficult? <a href="https://youtu.be/psPArQt_Cu8">View our guidance video</a></td>
                </tr>
            </tbody>
        </table>


    </div>
</div>

JuliaSearleTennis/Views/Juniors/MiniTennis.cshtml
@{
    ViewBag.Title = "MiniTennis";
    Layout = "~/Views/_LayoutPage.cshtml";
}
<link href="@Url.Content("~/CSS/BookingButtons.css")" rel="stylesheet" />
<link href="@Url.Content("~/CSS/JuniorBookingButtons.css")" rel="stylesheet" />
<!--=== Content Part ===-->
<div class="container content">
    <div class="row margin-bottom-40">
        <div class="col-md-6 md-margin-bottom-40">
            <h2>Mini Tennis (age 5-11yrs)</h2>
            <p>We offer a full Mini Tennis programme for children of all abilities</p>
            <ul class="list-unstyled">
                <li>
                    Maximum Ratio of 1:8
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Different coloured balls and modified court sizes
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	ABCs development (Agility, Balance and Co-ordination)
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Technical and Tactical coaching
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	End-of-term certificates for everyone
                </li>
                </ul>


              
        </div>

        <div class="col-md-6 md-margin-bottom-40">
            <div class="responsive-video">
                <iframe width="854" height="510" src="https://www.youtube.com/embed/HEwRNmyt69o" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div><!--/row-->
    <div class="row">

        <div class="row md-margin-bottom-40">
            Please note that all players who participate in the coaching programme MUST either be members of the club OR pay a guest fee to the club.
            Once your coaching registration is complete, the club will send you details regarding guest fee payment or membership application.
            The guest fee payable is equal to £1.50 per session for juniors and £2.50 per session for adults.
        </div>
        <script src="https://d3gxy7nm8y4yjr.cloudfront.net/js/embed.js" type="text/javascript"></script>
        <table cellspacing="5" class="table table-striped">
            <thead>
                <tr>
                    <th>Spring 2017 Wigmore classes</th>
                    <th>Autumn 2016 Camber classes</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td colspan="2">
                        <h3>Mini Red Tennis</h3>
                    </td>
                </tr>
                <tr>
                    <td>

                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>	Monday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Tuesday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Tuesday 5pm</li>
                            <li><i class="fa fa-check color-green"></i>	Wednesday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Thursday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Friday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Friday 5pm</li>
                            <li><i class="fa fa-check color-green"></i>	Saturday 9am</li>
                            <li><i class="fa fa-check color-green"></i>	Saturday 10am</li>
                        </ul>

                    </td>
                    <td>

                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>	Tuesday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Saturday 9am</li>
                            <li><i class="fa fa-check color-green"></i>	Saturday 11am </li>
                        </ul>

                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="@Url.Action("Red","Booking")"
                           class="RedMini">Book a red course at Wigmore</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Red","BookingCamber")"
                           class="RedMini">Book a red course at Camber</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <br /> If the course you wish to enrol for is fully booked you can join a waiting list.
                        <br />
                        <a class="RedMini" target="_blank"
                           href="https://docs.google.com/forms/d/1YlmozTfmfFfxmp_c1yQRKEs6rZazMI6b_MXxl510Jw4/viewform?usp=send_form">Join a waiting list</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h3>Mini Orange Tennis</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>	Monday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Tuesday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Tuesday 5pm</li>


                            <li><i class="fa fa-check color-green"></i>	Thursday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Friday 4pm</li>
                        </ul>

                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>	Monday 4pm</li>

                            <li><i class="fa fa-check color-green"></i>	Saturday 10am</li>
                        </ul>

                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="@Url.Action("Orange","Booking")"
                           class="OrangeMini">Book an orange course at Wigmore</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Orange","BookingCamber")"
                           class="OrangeMini">Book an orange course at Camber</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        If the course you wish to enrol for is fully booked you can join a waiting list.
                        <br />
                        <a class="OrangeMini" target="_blank"
                           href="https://docs.google.com/forms/d/1YlmozTfmfFfxmp_c1yQRKEs6rZazMI6b_MXxl510Jw4/viewform?usp=send_form">
                            Join a waiting list
                        </a>
                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <h3>Mini Green Tennis</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <ul class="list-unstyled">

                            <li><i class="fa fa-check color-green"></i>	Tuesday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Wednesday 4pm</li>

                            <li><i class="fa fa-check color-green"></i>	Friday 4pm</li>
                            <li><i class="fa fa-check color-green"></i>	Friday 5pm</li>

                        </ul>

                    </td>

                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>	Saturday 12pm</li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="@Url.Action("Green","Booking")"
                           class="GreenMini">Book a green course at Wigmore</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Green","BookingCamber")"
                           class="GreenMini">Book a green course at Camber</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        If the course you wish to enrol for is fully booked you can join a waiting list.
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <a class="GreenMini" target="_blank"
                           href="https://docs.google.com/forms/d/1YlmozTfmfFfxmp_c1yQRKEs6rZazMI6b_MXxl510Jw4/viewform?usp=send_form">
                            Join a waiting list
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>





    </div>
    <div class="row team margin-bottom-20">
        <h2>What is mini tennis?</h2>
        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/mini-red-image.jpg")" class="img-responsive">

                <h3>
                    Mini Tennis Red
                </h3>
               <i>(age 5-8yrs)</i>

                <p>
                    Mini red is an introduction to tennis, using light –weight rackets, sponge balls and a smaller court. A fun way to develop moving, hitting, throwing and catching skills and basic racket skills.
                </p>

            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/mini-orange-image.jpg")" class="img-responsive">
                <h3>Mini Tennis Orange</h3>
                <i>(age 8-9yrs)</i>
                <p>
                    Mini Orange is designed for beginners and improvers wanting to continue their tennis skills, rallying and serving using medium bounce balls and simple scoring.
                </p>

            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/mini-green-image.jpg")" class="img-responsive">
                <h3>Mini Tennis Green</h3>
                <i>         (age 10-11yrs)</i>

                <p>
                    Mini Green is the final stage in preparing for full tennis, working on technique, tactics as well as fundamental athletic skills. The aim is to get players to rally from the baseline and use full tennis scoring.
                </p>
            </div>
        </div>
    </div>

</div>

JuliaSearleTennis/Views/Juniors/PrivateLessons.cshtml
@{
    ViewBag.Title = "Private lessons";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<div class="container content">
    <div class="row">
        <h3>
            Private coaching
        </h3>
        <p>
            Private coaching sessions are the perfect opportunity for you to develop
            those areas of your game most important to you. Our Coaching Team are
            available seven days a week for private lessons (1-2 players) or private
            groups (3-4 players).
        </p>
        <p>
            Contact one of our coaches directly to book a private lesson,
            using the contact details provided on
            <a href="@Url.Action("OurCoachingTeam","Team")">
                Our Team page.
            </a>
            <br />
            If you would like to book a lesson with Julia Searle, our Head
            Coach, you can view her availability and book a lesson online
            using <a href="https://tenniscoaching.acuityscheduling.com/schedule.php?calendarID=160058"> the calendar here</a>
        </p>
        <div class="col-md-12">
            <div class="row margin-bottom-20">
                <div class="col-md-6">
                    <!-- Grey Panel -->
                    <div class="panel panel-grey">
                        <div class="panel-heading">
                            <h3 class="panel-title">Pricing</h3>
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Coach</th>
                                        <th>1 hour * (1-2 players)</th>
                                        <th>1 hour (3-4 players) </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr><td>Julia	</td><td>£30</td><td>£35</td></tr>
                                    <tr><td>Michael	</td><td>£28</td><td>£35</td></tr>
                                    <tr><td>Joe	    </td><td>£25</td><td>£35</td></tr>
                                    <tr><td>Jimmy	</td><td>£30</td><td>£35</td></tr>
                                    <tr><td>George	</td><td>£30</td><td>£35</td></tr>
                                    <tr><td>Michaela	</td><td>£28</td><td>£35</td></tr>
                                    <tr><td>Scott	</td><td>£25</td><td>£35</td></tr>
                                    <tr><td>Amy     </td><td>£20</td><td>£35</td></tr>
                                    <tr><td>Ava     </td><td>£25</td><td>£35</td></tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="3"> * 30 minute lessons available for £15</td>
                                    </tr>
                                </tfoot>

                            </table>


                        </div>
                    </div>
                    <!-- End Grey Panel -->

                   



                </div>
                <div class="col-md-6">
                    <!-- Red Panel -->
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title">Additional charges</h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                Priority for private lessons is given to members of the club. If you are not a member,
                                you will be asked to pay a guest fee of £4 for adults and £1.50 for juniors.
                            </p>
                            <p>
                                If your lesson requires the use of flood lights you will be asked to pay an additional floodlighting
                                fee as set by the club.
                            </p>
                        </div>
                    </div>
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title">What are Private groups? (3 - 4 players)</h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                Private groups can be booked as an alternative to the group coaching programme.
                            </p>
                            <p>
                                Private Groups cannot be arranged for more than four players. If you would like a larger group, we can add one to our regular term time coaching programme.
                            </p>

                        </div>
                    </div>
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title">What are private lessons?</h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                Private lessons can be shared for 1-2 players.
                            </p>

                        </div>
                    </div>
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title">Cancellation policy</h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                <ul class="list-unstyled">

                                    <li>	If you cancel your lesson with more than 48hours notice, you will not be charged</li>
                                    <li>	If you cancel your lesson with between 24-48hrs notice, you will be charged 50% of the lesson cost</li>
                                    <li>	If you cancel your lesson with less than 24hrs notice, you will be charged 100% of the lesson cost</li>
                                </ul>
                            </p>

                        </div>
                    </div>
                    <!-- End Red Panel -->
                </div>
            </div>
        </div><!--/col-md-9-->


    </div><!--/row-->
</div><!--/container-->
<!--=== End Content Part ===-->

JuliaSearleTennis/Views/Juniors/Tots.cshtml
@{
    ViewBag.Title = "Tots tennis";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<link href="@Url.Content("~/CSS/BookingButtons.css")" rel="stylesheet" />
<link href="@Url.Content("~/CSS/JuniorBookingButtons.css")" rel="stylesheet" />
<!--=== Content Part ===-->
<div class="container content">
    <div class="row margin-bottom-40">
        <div class="col-md-6 md-margin-bottom-40">
            <h2>Tots Tennis (age 3-4yrs)</h2>
            <p>We offer a full Tots Tennis programme to introduce children to the game</p>
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-check color-green"></i>Maximum Ratio of 1:6
                </li>
                <li>
                    <i class="fa fa-check color-green"></i> Soft balls, smaller racket and modified court sizes
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	ABCs development (Agility, Balance and Co-ordination)
                </li>
                <li>
                    <i class="fa fa-check color-green"></i> Learn tennis basics
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Lots of fun!
                </li>
                <li>
                    <i class="fa fa-check color-green"></i>	Stickers for everyone
                </li>
            </ul>
        </div>

        <div class="col-md-6 md-margin-bottom-40">
            <img src="@Url.Content("~/img/join-the-fun.jpg")" class="img-responsive" />
        </div>
    </div><!--/row-->
    <div class="row">

        <div class="row md-margin-bottom-40">
            Please note that all players who participate in the coaching programme MUST either be members of the club OR pay a guest fee to the club.
            Once your coaching registration is complete, the club will send you details regarding guest fee payment or membership application.
            The guest fee payable is equal to £1.50 per session for juniors and £2.50 per session for adults.
        </div>
        <table cellspacing="5" class="table table-striped">
            <thead>
                <tr>
                    <th>Spring 2017 Wigmore classes</th>
                    <th>Autumn 2016 Camber classes</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <ul class="list-unstyled">

                            <li><i class="fa fa-check color-green"></i>MONDAY 4PM (3-4 YRS)</li>
                            <li><i class="fa fa-check color-green"></i>TUESDAY 10:30AM (3-4 YRS)*</li>
                            <li><i class="fa fa-check color-green"></i>THURSDAY 4PM (3-4 YRS)</li>
                            <li><i class="fa fa-check color-green"></i>FRIDAY 10:30AM (3-4 YRS)*</li>
                            <li><i class="fa fa-check color-green"></i>FRIDAY 4PM (3-4 YRS)*</li>
                            <li><i class="fa fa-check color-green"></i>SATURDAY 10AM (3-4YRS)</li>
                        </ul>
                        <a href="@Url.Action("Tots","Booking")" class="TotsMini">Book a tots class at Wigmore</a>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>TUESDAY 3:30PM (3-4 YRS)</li>
                            <li><i class="fa fa-check color-green"></i>THURSDAY 10AM (3-4 YRS)</li>

                        </ul>
                        <a href="@Url.Action("Tots","BookingCamber")" class="TotsMini">Book a tots class at Camber</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">

                        <br />
                        If the course you wish to enrol for is fully booked you can join a waiting list.
                        <a href="https://docs.google.com/forms/d/1YlmozTfmfFfxmp_c1yQRKEs6rZazMI6b_MXxl510Jw4/viewform?usp=send_form" class="TotsMini">Join a waiting list</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">Finding booking difficult? <a href="https://youtu.be/psPArQt_Cu8">View our guidance video</a></td>
                </tr>

            </tbody>
        </table>


    </div>
    <div class="row team margin-bottom-20">

        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/tots1.jpg")" class="img-responsive">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/tots2.jpg")" class="img-responsive">


            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail-style">
                <img alt="" src="@Url.Content("~/img/tots3.jpg")" class="img-responsive">

            </div>
        </div>
    </div>

</div>